rules:
  indent:
    - 2
    - tab
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  comma-dangle:
    - 1
    - always-multiline
env:
  es6: true
  node: true
  browser: true
extends: 'eslint:recommended'

parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module'
  }
