extends:
  - stylelint-config-standard

rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - function
        - return
        - extend
        - if
        - else
        - error
        - each
        - while
        - for
        - include
        - mixin
