baseurl = "http://craveytrain.com"
languageCode = "en-us"
title = "Craveytrain"

[params]
author = "Mike Cravey"
description = "The personal site of Mike Cravey (@craveytrain)."
subtitle = "I'm a little geek bot, short and stout…"
