version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: mkdir -p ~/reports
      - run:
          name: Lint
          command: yarn lint --format junit --output-file ~/reports/eslint-results.xml
          when: always
      - run:
          name: Test
          command: node_modules/.bin/tape tests/**/*.js | node_modules/.bin/tap-xunit > ~/reports/test-results.xml
          when: always
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
  deploy:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn build
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            make build
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            make deploy
workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
  deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
